### PR TITLE
clock_gettime require -lrt to link

### PR DESCRIPTION
**Pull request by imharrywu**
latency test use posix API: clock_gettime() in `rt'

### CODE REVIEW

**Comment by imharrywu** [comment]
on linux (ubuntu-12.04 x86)

**Comment by dale-wilson** [comment]
This is a cross-platform project which runs on Windows as well as Linux.  You can't use platform-specific functions directly unless you provide an alternative implementation for other platforms.

http://stackoverflow.com/questions/5404277/porting-clock-gettime-to-windows  shows one way to do it, but that's a lot of code.

**Comment by netmonk** [comment]
Well, if you want to achieve  best possible performance you have to stick to one plateform and use all tradeoff from it.

**Comment by dale-wilson** [comment]
As part of the recent reorganization a Windows implementation of clock_gettime() is in test/latency/clock_gettime.h.  #ifdef's are use to determine which clock_gettime() function gets called.  The latency test is the only one that uses it.  

I'm going to close this pull request because it doesn't apply to the current source code.

**Pull request closed without merging**
